### ISSUE TITLE
Admin page filters (sort) not working correctly.

### ISSUE THREAD

**Issue by samz9n** [LibraryProjectGroup/library-project-frontend#182]
```[tasklist]
### Tasks
- [x] Sort in alphabetical order
- [x] Add Office filtering
- [x] Delete unused filters on e.g. delete buttons etc.
```
