### ISSUE TITLE
Creating tests for current user stories

### ISSUE THREAD

**Issue by AnjaMis** [LibraryProjectGroup/library-project-frontend#4]
1. acceptance tests that are run based on the acceptance criteria for the user stories 

- [x] Test for LibraryProjectGroup/library-project#23 
- [x] Test for LibraryProjectGroup/library-project#36 
- [x] Test for LibraryProjectGroup/library-project#24 
- [x] Test for LibraryProjectGroup/library-project#37 
- [x] Test for LibraryProjectGroup/library-project#38 
- [x] Test for LibraryProjectGroup/library-project#47 
- [x] Test for deleting a book from the catalog
